name: Daily Build

on:
  # Trigger build manually
  workflow_dispatch:

  # Runs every day at 1pm GMT (2pm CEST)
  schedule:
    - cron: '0 13 * * *'

jobs:
  trigger-pages-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $TOKEN"
        env:
          TOKEN: ${{ secrets.BUILD_TOKEN }}